# Generated by Django 4.2.7 on 2023-11-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewear_app', '0002_uploadimage_delete_movie_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
