# Generated by Django 4.2.7 on 2023-11-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewear_app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Outerwear', 'Outerwear'), ('Shoes', 'Shoes'), ('Assosories', 'Assosories'), ('Dresses', 'Dresses'), ('Shirt', 'Shirt')], max_length=200),
        ),
    ]
