# Generated by Django 4.2.7 on 2023-11-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewear_app', '0005_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('XXXS', 'Three XS'), ('XXS', 'Extra Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Meduim'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('XXL', 'Three XL'), ('Other', 'Other')], max_length=200),
        ),
    ]
